<!DOCTYPE html>
<html>
    <head>
        <title>sim800 data test</title>		
		<style>
		.infoBox {
			width: 350px;
			height: 100px;
			position: absolute;
			left: 50px;
			font-size:120%;
			color: Navy;
			text-align: center;
			vertical-align: middle;			
			margin-left: auto;
			margin-right: auto;
		}
		#screen {
			width: 450px;
			height: 530px;
			text-align: center;
			vertical-align: middle;
			background-color: LightGray;
			font-size:120%;
			position: relative;
			margin-left: auto;
			margin-right: auto;
			top: 50px;			 
		}
			#data {
			  background-color: Orange;
			  bottom: 380px;
			}
			
			#connect_time {
			  background-color: Tomato;
			  bottom: 270px;
			}
			#sim800_Stime {			  			  
			  background-color: MediumSeaGreen;
			  bottom: 160px;
			}
			#detect_time {
			  background-color: DodgerBlue;
			  bottom: 50px;  
			}
		</style>
    </head>
    <body>      
		<div id = "screen">
			<div class = "infoBox" id = "data">
				<h4>Host. System Time</h4>
				<!-- <button type="button" onclick="loadDoc()">Change Content</button> -->
			</div>			
			<div class = "infoBox" id = "connect_time"> <h5>Hostinger<br>Data transfer time</h5> </div>
			<div class = "infoBox" id = "sim800_Stime"> <h4>sim800<br>Data transfer time</h4> </div>
			<div class = "infoBox" id = "detect_time"> <h5>sim800<br>Truck detection time</h5> </div>
		</div>
		   
    </body>
	
		<script type="text/javascript">
			
			window.onload = function() {  
				let t = setInterval(serverExchange, 500); 
			}
			
			function getHostTime() {
				var xhttp = new XMLHttpRequest();
				xhttp.onreadystatechange = function() {
					if (this.readyState == 4 && this.status == 200) {
						document.getElementById("data").innerHTML = this.responseText;
					}
				};
				xhttp.open("GET", "host_time.php", true);  
				xhttp.send();
			}
			
			function getTruckData() {
				var xhttpT = new XMLHttpRequest();
				xhttpT.onreadystatechange = function() {
					
					if (this.readyState == 4 && this.status == 200) {
						timeDataParse(this.responseText); 
					}
				};
				xhttpT.open("GET", "sim800truck_data.txt", true);  
				xhttpT.send();
			} 
			
			function timeDataParse(InitialStr = "") {
				$Hrtc = dataParse(InitialStr, "$Hrtc");				// Time (H,M,S) from sim800 RTC, generated by sim800connect.php script
				$Mrtc = dataParse(InitialStr, "$Mrtc"); 
				$Srtc = dataParse(InitialStr, "$Srtc"); 
				
				$Htruck = dataParse(InitialStr, "$Htruck", 10);		// Time (H,M,S) where sim800 detected a truck (sim800connect.php script)
				$Mtruck = dataParse(InitialStr, "$Mtruck", 10); 
				$Struck = dataParse(InitialStr, "$Struck", 10); 
				
				$servT = dataParse(InitialStr, "$servT", 9, 8); // Time (H,M,S) where the server received data from sim800 (sim800connect.php script), 9 - offset of the data, 8 - data length
				
				document.getElementById("connect_time").innerHTML = "<h4>Server<br>Data received: " + $servT + "</h4>";		
				document.getElementById("sim800_Stime").innerHTML = "<h4>sim800 Modem<br>Data send: " + $Hrtc + ":" + $Mrtc + ":" + $Srtc + "</h4>";		
				document.getElementById("detect_time").innerHTML = "<h4>sim800 Core<br>Truck detected: " + $Htruck + ":" + $Mtruck + ":" + $Struck + "</h4>";					
			}
			
			function dataParse(InitialStr = "", searchStr = "", data1stPos = 8, dataLength = 2) {
				var pos = InitialStr.indexOf(searchStr) + data1stPos;
				return InitialStr.slice(pos, pos + dataLength);
			}
			
			function serverExchange() {
				getHostTime();
				getTruckData();
			}
			
		</script>
</html>

